# Generated by Django 4.0.6 on 2022-07-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_massage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Massage',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='title',
        ),
    ]
