# Generated by Django 4.0.6 on 2022-07-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_delete_massage_rename_name_ticket_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='body',
            new_name='description',
        ),
    ]
